name: Playwright E2E

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-playwright.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      backend:
        image: eclipse-temurin:17
        options: >-
          --entrypoint /bin/bash
        ports:
          - 8080:8080
        env:
          SEED_TEST_USERS: 'true'
        volumes: []

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend
        working-directory: backend
        run: mvn -DskipTests -B package

      - name: Start backend (jar) with seeded users
        working-directory: backend
        run: |
          nohup java -DSEED_TEST_USERS=true -jar target/task-management-backend-0.0.1-SNAPSHOT.jar > backend.log 2>&1 &

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/actuator/health >/dev/null; then
              echo "backend ready"; break; fi
            echo "waiting for backend..."; sleep 2; done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: frontend
        env:
          CI: true
        run: npx playwright test --reporter=dot

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
